resolver: lts-16.16

packages:
- iwlib-git
- xmobar-git
- xmonad-git
- xmonad-contrib-git

extra-deps:
#- X11-1.9
#- alsa-mixer-0.3.0
#- parsec-numbers-0.1.0
- netlink-1.1.1.0
- timezone-olson-0.1.9

flags:
  xmobar:
    all_extensions: true
